services:
  react-app:
    build:
      context: .
    container_name: pokedex-react-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
